@startuml

class DisplayExecution{

- Scanner
    - ArrayList<String> List
    + addList();
    + deleteList();
    + EditTitle();
    + SaveList();
    + Display();
    + CheckStatus();
    + SaveAllListClicked();
    + SaveOneListClicked();
    + OpenOneListClicked();
    + OpenAllListClicked();
    + DisplayIncomplete();
    + updateList();
}
Application--o DisplayExecution

@enduml